In [20]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import nltk

In [21]:
amazon=pd.read_csv("G:/DATA/Python/amazonreviews.tsv",sep='\t')


In [22]:
amazon.head()

label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [23]:
# build a model that can classify positive and negative reviews

In [24]:
amazon.shape

(10000, 2)

In [25]:
amazon.label.value_counts()

neg    5097
pos    4903
Name: label, dtype: int64

In [26]:
amazon.label.replace({"neg":0,"pos":1},inplace=True)

In [27]:
amazon.head()

label                                             review
0      1  Stuning even for the non-gamer: This sound tra...
1      1  The best soundtrack ever to anything.: I'm rea...
2      1  Amazing!: This soundtrack is my favorite music...
3      1  Excellent Soundtrack: I truly like this soundt...
4      1  Remember, Pull Your Jaw Off The Floor After He...

In [28]:
# first we convert everything into lower case
amazon.review= amazon.review.str.lower()

In [29]:
amazon.head(2)

label                                             review
0      1  stuning even for the non-gamer: this sound tra...
1      1  the best soundtrack ever to anything.: i'm rea...

In [30]:
import string

In [31]:
# to check for stopwords we 
from nltk.corpus import stopwords


In [32]:
#we can see the list of stopwords in english

stopwords.words("english")

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [33]:
def text_process(mess):
    """
    1. remove the punctuation
    2. remove the stopwords
    3.return the list of clean textwords
    """
    nopunc=[char for char in mess if char not in string.punctuation]
    nopunc="".join(nopunc)
    
    return[word for word in nopunc.split() if word not in stopwords.words("english")]

In [34]:
#amazon["review"].apply(text_process)

In [35]:
# count vectorizer returns the counts of words 
from sklearn.feature_extraction.text import CountVectorizer

bow_transformer= CountVectorizer(analyzer=text_process).fit(amazon["review"])

In [36]:
# tell us how many times a specific word has appeared
bow_transformer.vocabulary_

{'stuning': 34189,
 'even': 12595,
 'nongamer': 24278,
 'sound': 33125,
 'track': 36325,
 'beautiful': 3941,
 'paints': 25720,
 'senery': 31523,
 'mind': 22665,
 'well': 38818,
 'would': 39538,
 'recomend': 29102,
 'people': 26193,
 'hate': 16497,
 'vid': 38116,
 'game': 14941,
 'music': 23568,
 'played': 26823,
 'chrono': 6964,
 'cross': 8903,
 'games': 14971,
 'ever': 12608,
 'best': 4239,
 'backs': 3531,
 'away': 3391,
 'crude': 8936,
 'keyboarding': 19746,
 'takes': 34897,
 'fresher': 14581,
 'step': 33794,
 'grate': 15807,
 'guitars': 16080,
 'soulful': 33109,
 'orchestras': 25171,
 'impress': 17969,
 'anyone': 2530,
 'cares': 6094,
 'listen': 20917,
 'soundtrack': 33147,
 'anything': 2538,
 'im': 17820,
 'reading': 28886,
 'lot': 21215,
 'reviews': 30044,
 'saying': 30943,
 'figured': 13711,
 'id': 17672,
 'write': 39594,
 'review': 30033,
 'disagree': 10372,
 'bit': 4457,
 'opinino': 25096,
 'yasunori': 39747,
 'mitsudas': 22881,
 'ultimate': 37007,
 'masterpiece': 21946,
 'time

In [37]:
# creating a term document matrix
amazon_tdm= bow_transformer.transform(amazon.review)

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
# Sampling of tdm
x_train,x_test, y_train, y_test= train_test_split(amazon_tdm, amazon.label, test_size=.2)

In [43]:
from sklearn.metrics import confusion_matrix

In [44]:
#logistic 
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()


In [45]:
logreg.fit(x_train,y_train)
pred_logreg=logreg.predict(x_test)
tab_logreg=confusion_matrix(pred_logreg,y_test)
tab_logreg

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[870, 153],
       [148, 829]], dtype=int64)

In [46]:
acc_logreg= tab_logreg.diagonal().sum()/tab_logreg.sum()
acc_logreg

0.8495

# Decision tree

In [48]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

In [49]:
#decision Tree
dt.fit(x_train,y_train)
pred_dt=dt.predict(x_test)
tab_dt=confusion_matrix(pred_dt,y_test)
tab_dt

array([[764, 290],
       [254, 692]], dtype=int64)

In [50]:
acc_dt= tab_dt.diagonal().sum()/tab_dt.sum()
acc_dt

0.728

# RandomForest

In [51]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [52]:
# random forest
rf.fit(x_train,y_train)
pred_rf= rf.predict(x_test)
tab_rf=confusion_matrix(pred_rf, y_test)
tab_rf

array([[861, 183],
       [157, 799]], dtype=int64)

In [53]:
acc_rf= tab_rf.diagonal().sum()/tab_rf.sum()
acc_rf

0.83

# NAIVE BAYES

In [54]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()

In [55]:
# Naivebaye
nb.fit(x_train,y_train)
pred_nb=nb.predict(x_test)
tab_nb=confusion_matrix(pred_nb,y_test)
tab_nb


array([[881, 169],
       [137, 813]], dtype=int64)

In [56]:
acc_nb= tab_nb.diagonal().sum()/tab_nb.sum()
acc_nb

0.847

# sentiment classification


In [58]:
nltk.download("vader_lexicon") # This is a dictionary

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...


True

In [59]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [60]:
sent=SentimentIntensityAnalyzer()

In [61]:
# gives the polarity of a particular review
sent.polarity_scores("this drink was horrible. i had a bad feeling by taking a sip")

{'neg': 0.452, 'neu': 0.452, 'pos': 0.097, 'compound': -0.7579}

In [62]:
sent.polarity_scores("this drink was awesome. i had a heavenly feeling by taking a sip")

{'neg': 0.0, 'neu': 0.422, 'pos': 0.578, 'compound': 0.8625}

In [ ]:
# now suppose if ratings column is not there in amazon dataset

In [63]:
# it takes input one sentence at a time
abc= sent.polarity_scores(amazon.iloc[0][1])


In [64]:
abc.keys()

dict_keys(['neg', 'neu', 'pos', 'compound'])

In [65]:
abc["compound"]

0.9454

In [67]:
# writng a for loop to find all scores
score_com=[]
score_pos=[]
score_neg=[]

for i in range(0,amazon.shape[0]):
    score=sent.polarity_scores(amazon.iloc[i][1])
    score1=score["compound"]
    score_com.append(score1)
    
    score2=score["pos"]
    score_pos.append(score2)
    
    score3=score["neg"]
    score_neg.append(score3)

In [68]:
amazon["comp_score"]=score_com
amazon["pos_score"]=score_pos
amazon["neg_score"]=score_neg

In [69]:
# in this way we can explore whether the comments were positive or negative
amazon.head()


label                                             review  comp_score  \
0      1  stuning even for the non-gamer: this sound tra...      0.9454   
1      1  the best soundtrack ever to anything.: i'm rea...      0.8957   
2      1  amazing!: this soundtrack is my favorite music...      0.9858   
3      1  excellent soundtrack: i truly like this soundt...      0.9814   
4      1  remember, pull your jaw off the floor after he...      0.9781   

   pos_score  neg_score  
0      0.243      0.088  
1      0.145      0.018  
2      0.268      0.040  
3      0.295      0.090  
4      0.254      0.000